% Note that the following scripts/commands should be called from the installation 
% directory of the code.

% test the object detection pipeline with the Reduced MR-CNN recogniton
% model and the LocNet InOut localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_LocNet_InOut','bbox_proposals','edge_boxes','gpu_id',1);
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_LocNet_InOut','bbox_proposals','selective_search','gpu_id',1);
% test the object detection pipeline with the Reduced MR-CNN recogniton
% model and the LocNet Borders localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_LocNet_Borders','bbox_proposals','edge_boxes','gpu_id',1);
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_LocNet_Borders','bbox_proposals','selective_search','gpu_id',1);
% test the object detection pipeline with the Reduced MR-CNN recogniton
% model and the LocNet Combined localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_LocNet_Combined','bbox_proposals','edge_boxes','gpu_id',1);
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_LocNet_Combined','bbox_proposals','selective_search','gpu_id',1);
% test the object detection pipeline with the Reduced MR-CNN recogniton
% model and the CNN-based bounding box regression model:
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_BBoxReg','bbox_proposals','edge_boxes','gpu_id',1);
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_BBoxReg','bbox_proposals','selective_search','gpu_id',1);

% test the object detection pipeline with the Fast RCNN recogniton
% model and the LocNet InOut localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_LocNet_InOut','bbox_proposals','edge_boxes','gpu_id',1);
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_LocNet_InOut','bbox_proposals','selective_search','gpu_id',1);
% test the object detection pipeline with the Fast RCNN recogniton
% model and the LocNet Borders localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_LocNet_Borders','bbox_proposals','edge_boxes','gpu_id',1);
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_LocNet_Borders','bbox_proposals','selective_search','gpu_id',1);
% test the object detection pipeline with the Fast RCNN recogniton
% model and the LocNet Combined localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_LocNet_Combined','bbox_proposals','edge_boxes','gpu_id',1);
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_LocNet_Combined','bbox_proposals','selective_search','gpu_id',1);
% test the object detection pipeline with the Fast RCNN recogniton
% model and the CNN-based bounding box regression model:
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_BBoxReg','bbox_proposals','edge_boxes','gpu_id',1);
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_BBoxReg','bbox_proposals','selective_search','gpu_id',1);


% Testing the object detection pipeline when the input candidate bounding
% boxes are generated by a sliding window scheme.

% Reduced MR-CNN recogniton model & LocNet InOut localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_LocNet_InOut','bbox_proposals','dense_boxes_10k','nms_init',0.85,'gpu_id',1);
% Reduced MR-CNN recogniton model & LocNet Borders localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_LocNet_Borders','bbox_proposals','dense_boxes_10k','nms_init',0.85,'gpu_id',1);
% Reduced MR-CNN recogniton model & LocNet Combined localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_LocNet_Combined','bbox_proposals','dense_boxes_10k','nms_init',0.85,'gpu_id',1);
% Reduced MR-CNN recogniton model & CNN-based bounding box regression model:
script_test_object_detection_pipeline_PASCAL('VGG16_Reduced_MRCNN','VGG16_BBoxReg','bbox_proposals','dense_boxes_10k','nms_init',0.85,'gpu_id',1);

% Fast RCNN recogniton model & LocNet InOut localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_LocNet_InOut','bbox_proposals','dense_boxes_10k','nms_init',0.85,'gpu_id',1);
% Fast RCNN recogniton model & LocNet Borders localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_LocNet_Borders','bbox_proposals','dense_boxes_10k','nms_init',0.85,'gpu_id',1);
% Fast RCNN recogniton model & LocNet Combined localiton model:
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_LocNet_Combined','bbox_proposals','dense_boxes_10k','nms_init',0.85,'gpu_id',1);
% Fast RCNN recogniton model & CNN-based bounding box regression model:
script_test_object_detection_pipeline_PASCAL('VGG16_FastRCNN','VGG16_BBoxReg','bbox_proposals','dense_boxes_10k','nms_init',0.85,'gpu_id',1);







